# elm2gcam_mapping_generator.py
#
# Python translation of the elm2gcam portion of e3sm_gcam_land_mapping.r
# (original R script by Alan Di Vittorio).
#
# PURPOSE:
#   Generates spatial mapping files that link each ELM (E3SM Land Model) grid
#   cell to one or more GCAM (Global Change Assessment Model) land units.
#   Each land unit is a region x GLU (Geographic Land Unit / basin) combination.
#   The output CSVs record what fraction ("Weight") of each ELM cell belongs to
#   each GCAM region+GLU, based on the MOIRAI high-resolution land-area raster.
#
# WORKFLOW:
#   Step 1 - Read base context data
#     - Parse woodharvest.xml to get the ordered list of GCAM land units
#       (region x basin combinations used by the IAC coupler).
#     - Read MOIRAI_reggcam_GLU_with_spaces.csv for region codes/names.
#     - Read basin_to_country_mapping.csv for GLU abbreviations and basin IDs.
#     - Build gcam_lu: a lookup table with out_reg_code, out_lu_code,
#       out_basin_code, gcam_reg_name, basin_abr, gcam_reg_code, gcam_basin_code.
#
#   Step 2 - Load high-resolution geospatial grids
#     - Open moirai_valid_region32_water_basin235.bsq: a 2160x4320 (5 arcminute)
#       raster where each pixel value = region_code * 10000 + GLU_code.
#     - Read hyde_cell_plus.bil and hyde_land_plus.bil for cell and land areas (km^2).
#     - Extrapolate missing cell-area values across each latitude band.
#
#   Step 3 - High-resolution US state boundary logic (computed but not used in output)
#     - Rasterize gcamusa_state_glu_wgs84.shp onto the MOIRAI grid.
#     - Apply a 7x7 focal-majority filter to fill USA region pixels without a
#       state assignment with the dominant neighboring state ID.
#     - Build moirai_state_rast (region x GLU code raster with state sub-regions
#       replacing the single USA region inside the contiguous US).
#     NOTE: moirai_state_rast is computed but not used in the output loop; the
#           _usa mapping files generated by the R script are not produced here.
#
#   Step 4 - Core mapping extraction logic (_pixel_fracs + process_elm_cell)
#     - For a single coarse ELM cell (identified by a flat cell index), compute
#       its lat/lon bounding box from the pre-calculated boundary arrays.
#     - Cells that straddle the dateline (e.g. the cell centred at 180 deg in
#       the f09/f19 grids) are handled as two horizontal strips that are
#       concatenated before aggregation.
#     - For each fine MOIRAI pixel in the window, _pixel_fracs() computes its
#       fractional overlap with the ELM cell polygon via an outer product of
#       1-D lon and lat overlap vectors, replicating R's
#       raster::extract(..., exact=TRUE) weighting.
#     - weighted_land_area = pixel_overlap_fraction x land_area for each pixel.
#     - Weight for each GCAM land unit = sum(weighted_land_area for LU) /
#       sum(weighted_land_area for all valid pixels in cell).
#     - Weights are normalised to 1 when some raster LU codes are absent from
#       gcam_lu (matches R: if(sumw < 1) weight = 1/sumw * weight).
#     - Results are merged with the gcam_lu lookup table to attach
#       region/GLU identifiers.
#
#   Step 5 - Loop through ELM grid resolutions
#     - Iterates over five ELM surface data files (0.9, 1.9, 0.5, 0.125, 0.25 deg),
#       reading LONGXY/LATIXY to derive cell boundaries.
#     - Calls process_elm_cell for every grid cell and concatenates results.
#     - Writes one CSV per resolution to ./mapping_outfiles/:
#         region_index, GLU_index, x (1-based lon index), y (1-based lat index),
#         gcam_reg_name, GLU_name, Weight
#
# INPUT FILES (all under /global/cfs/cdirs/e3sm/inputdata/iac/giac/inputs_for_mapping_generation/):
#   woodharvest.xml, MOIRAI_reggcam_GLU_with_spaces.csv,
#   basin_to_country_mapping.csv, moirai_valid_region32_water_basin235.bsq,
#   hyde_cell_plus.bil, hyde_land_plus.bil,
#   gcamusa_state_glu_wgs84/gcamusa_state_glu_wgs84.shp,
#   surfdata_0.9x1.25_HIST_simyr2015_c201021.nc,
#   surfdata_1.9x2.5_SSP5_RCP85_simyr2015_c210916.nc,
#   surfdata_0.5x0.5_HIST_simyr2015_c220318.nc,
#   surfdata_0.125x0.125_HIST_simyr2015_c241205.nc,
#   surfdata_0.25x0.25_simyr2015_c250312.nc
#
# OUTPUT FILES (written to ./mapping_outfiles/):
#   elm0.9x1.25togcam_mapping.csv, elm1.9x2.5togcam_mapping.csv,
#   elm0.5x0.5togcam_mapping.csv, elm0.125x0.125togcam_mapping.csv,
#   elm0.25x0.25togcam_mapping.csv

import os
import sys
import numpy as np
import pandas as pd
import xarray as xr
import geopandas as gpd
from shapely.geometry import Polygon
import rasterio
from rasterio.features import rasterize
from datetime import datetime
import pyproj

# Manually point PROJ to your active conda environment data directory
if "CONDA_PREFIX" in os.environ:
    proj_data_path = os.path.join(os.environ["CONDA_PREFIX"], "share", "proj")
    if os.path.exists(proj_data_path):
        os.environ["PROJ_DATA"] = proj_data_path  # For newer pyproj/PROJ versions
        os.environ["PROJ_LIB"] = proj_data_path   # For older PROJ versions
        pyproj.datadir.set_data_dir(proj_data_path)

# --- CONFIGURATION & PATHS ---
INPUTDATA_DIR = "/global/cfs/cdirs/e3sm/inputdata"
INPUT_DIR = os.path.join(INPUTDATA_DIR, "iac/giac/inputs_for_mapping_generation")
NEW_DIR = "./mapping_outfiles"
BTOL = 1e-6

os.makedirs(NEW_DIR, exist_ok=True)

print(f"Starting elm2gcam mapping generation at: {datetime.now()}")

# --- STEP 1: READ BASE CONTEXT DATA ---
# Read land unit list from woodharvest.xml
import xml.etree.ElementTree as ET
wh_xml_fn = os.path.join(INPUT_DIR, "woodharvest.xml")
tree = ET.parse(wh_xml_fn)
root = tree.getroot()
# Find the land unit strings inside the second child container
land_units = [node.text for node in root[1] if node.text is not None]

# Parse out unique output regions
# Emulate the R layout parsing regional dataframes
moirai_codes_fn = os.path.join(INPUT_DIR, "MOIRAI_reggcam_GLU_with_spaces.csv")
moirai_codes = pd.read_csv(moirai_codes_fn, skiprows=4)

gcam_basin2ctry_fn = os.path.join(INPUT_DIR, "basin_to_country_mapping.csv")
gcam_basin2ctry = pd.read_csv(gcam_basin2ctry_fn, skiprows=7)

# Build out region matching lists matching R's exact logic
reg_list = moirai_codes[['gcam_reg_code', 'gcam_reg_name']].drop_duplicates().reset_index(drop=True)
gcam_lu = pd.DataFrame({'land_unit': land_units})
gcam_lu['out_lu_code'] = range(1, len(gcam_lu) + 1)
gcam_lu['gcam_reg_name'] = None
gcam_lu['gcam_reg_code'] = None
gcam_lu['basin_abr'] = None

for _, row in reg_list.iterrows():
    mask = gcam_lu['land_unit'].str.startswith(row['gcam_reg_name'])
    gcam_lu.loc[mask, 'gcam_reg_name'] = row['gcam_reg_name']
    gcam_lu.loc[mask, 'gcam_reg_code'] = row['gcam_reg_code']
    # Extract the basin abbreviation suffix
    gcam_lu.loc[mask, 'basin_abr'] = gcam_lu.loc[mask, 'land_unit'].apply(lambda x: x[len(row['gcam_reg_name'])+1:])

out_reg_list = pd.DataFrame({'gcam_reg_name': gcam_lu['gcam_reg_name'].unique()})
out_reg_list['out_reg_code'] = range(1, len(out_reg_list) + 1)

gcam_lu = gcam_lu.merge(out_reg_list, on='gcam_reg_name', how='inner')
gcam_basin_sub = gcam_basin2ctry[['GCAM_basin_ID', 'Basin_name', 'GLU_name']].rename(columns={'GCAM_basin_ID': 'gcam_basin_code', 'GLU_name': 'basin_abr'})
gcam_lu = gcam_lu.merge(gcam_basin_sub, on='basin_abr', how='inner')
gcam_lu['out_basin_code'] = gcam_lu.groupby('out_reg_code').cumcount() + 1

# --- STEP 2: LOAD HIGH-RESOLUTION GEOSPATIAL GRIDS ---

# Open the moirai valid region map raster
moirai_fn = os.path.join(INPUT_DIR, "moirai_valid_region32_water_basin235.bsq")

with rasterio.open(moirai_fn) as src:
    transform = src.transform
    moirai_shape = src.shape
    lon_origin = src.bounds.left
    lat_origin = src.bounds.top
    res_x = src.res[0]
    res_y = src.res[1]

with xr.open_dataset(moirai_fn, engine='rasterio') as ds_moirai:
    var_name = list(ds_moirai.data_vars)[0]
    moirai_rast = ds_moirai[var_name].values[0]

def read_hyde_binary(filename):
    path = os.path.join(INPUT_DIR, filename)
    data = np.fromfile(path, dtype='<f4')
    data[data == -9999] = np.nan
    return data.reshape((2160, 4320))

moirai_cell_area = read_hyde_binary("hyde_cell_plus.bil")
moirai_land_area = read_hyde_binary("hyde_land_plus.bil")

# Extrapolate missing cell values across longitude bands like the R script logic
for i in range(moirai_cell_area.shape[0]):
    row = moirai_cell_area[i, :]
    if np.isnan(row).all():
        continue
    row[np.isnan(row)] = np.nanmin(row)

# --- STEP 3: HIGH RESOLUTION STATE BOUNDARY LOGIC ---
gcam_usa_state_fn = os.path.join(INPUT_DIR, "gcamusa_state_glu_wgs84/gcamusa_state_glu_wgs84.shp")
state_vector = gpd.read_file(gcam_usa_state_fn)
state_vector['state_id'] = state_vector['state_id'].astype(int) + 50
max_state_id = int(state_vector['state_id'].max())

# Rasterize state shapes onto the same grid layout
in_state_rast = rasterize(
    [(geom, pid) for geom, pid in zip(state_vector.geometry, state_vector.state_id)],
    out_shape=moirai_rast.shape,
    transform=transform,
    fill=0,
    all_touched=False,
    dtype=np.int32
)
in_state_rast = np.where(in_state_rast == 0, np.nan, in_state_rast)

# Process moving window filter using SciPy to find dominant states
from scipy.ndimage import generic_filter
def fill_usa_dom(buffer):
    center_idx = len(buffer) // 2
    focal_val = buffer[center_idx]
    if focal_val > max_state_id and not np.isnan(focal_val):
        valid_neighbors = buffer[(buffer < 10000) & (~np.isnan(buffer))]
        if len(valid_neighbors) > 0:
            vals, counts = np.unique(valid_neighbors, return_counts=True)
            return vals[np.argmax(counts)]
    return focal_val

# Apply 7x7 focal box filter
filter_rast = np.where(moirai_rast >= 20000, np.nan, in_state_rast)
state_rast = generic_filter(filter_rast, fill_usa_dom, size=(7, 7))

basin_rast = moirai_rast % 10000
state_rast_coded = state_rast * 10000 + basin_rast
moirai_state_rast = np.where(np.isnan(state_rast_coded), moirai_rast, state_rast_coded)

# --- STEP 4: CORE MAPPING EXTRACTION LOGIC ---
elm_surf_fns = [
    "surfdata_0.9x1.25_HIST_simyr2015_c201021.nc",
    "surfdata_1.9x2.5_SSP5_RCP85_simyr2015_c210916.nc",
    "surfdata_0.5x0.5_HIST_simyr2015_c220318.nc",
    "surfdata_0.125x0.125_HIST_simyr2015_c241205.nc",
    "surfdata_0.25x0.25_simyr2015_c250312.nc"
]

elm2gcam_ons = [
    "elm0.9x1.25togcam_mapping.csv", "elm1.9x2.5togcam_mapping.csv",
    "elm0.5x0.5togcam_mapping.csv", "elm0.125x0.125togcam_mapping.csv",
    "elm0.25x0.25togcam_mapping.csv"
]

def _pixel_fracs(r_s, r_e, c_s, c_e, lnmin_clip, lnmax_clip, ltmin, ltmax,
                 lon_origin, lat_origin, res_x, res_y):
    """Fractional area of each pixel that falls inside the given lon/lat rectangle.

    Replicates R's raster::extract(..., exact=TRUE) weighting: boundary pixels
    get a fraction < 1 proportional to their actual overlap area.
    Returns a (nrows, ncols) array with values in [0, 1].
    """
    px_lefts = lon_origin + np.arange(c_s, c_e) * res_x           # left edge of each col
    px_tops  = lat_origin - np.arange(r_s, r_e) * res_y            # top  edge of each row
    lon_ov = np.maximum(0.0,
                        np.minimum(px_lefts + res_x, lnmax_clip) -
                        np.maximum(px_lefts,          lnmin_clip))  # (ncols,)
    lat_ov = np.maximum(0.0,
                        np.minimum(px_tops,           ltmax) -
                        np.maximum(px_tops - res_y,   ltmin))       # (nrows,)
    return np.outer(lat_ov, lon_ov) / (res_x * res_y)              # (nrows, ncols)


def process_elm_cell(cell, num_lon, lonW, lonE, latS, latN, grid_rast, gcam_lu_df,
                     lon_origin, lat_origin, res_x, res_y):
    """Processes weights for a single coarse grid cell over finer spatial arrays."""
    lt = int(cell // num_lon)
    ln = int(cell % num_lon)

    lnmin, lnmax = lonW[lt, ln], lonE[lt, ln]
    ltmin, ltmax = latS[lt, ln], latN[lt, ln]

    ltmin = max(ltmin, -90.0)
    ltmax = min(ltmax, 90.0)

    # Latitude rows are the same regardless of dateline handling.
    row_top    = int(np.floor((lat_origin - ltmax) / res_y + 1e-9))
    row_bottom = int(np.floor((lat_origin - ltmin) / res_y - 1e-9))
    r_start, r_end = min(row_top, row_bottom), max(row_top, row_bottom)
    r_s = int(max(0, min(r_start, grid_rast.shape[0])))
    r_e = int(max(0, min(r_end + 1, grid_rast.shape[0])))
    if r_s == r_e:
        return None

    # After pre-normalisation to [-180, 180], lnmin > lnmax means the cell
    # genuinely straddles the dateline (e.g. the cell centred at 180° in the
    # f09/f19 grids).  Build two horizontal strips and concatenate them.
    raster_right = lon_origin + grid_rast.shape[1] * res_x  # = 180.0

    if lnmin > lnmax:
        # Right strip: lnmin → right edge of raster
        c_s_r = int(max(0, int(np.floor((lnmin - lon_origin) / res_x + 1e-9))))
        c_e_r = grid_rast.shape[1]

        # Left strip: left edge of raster → lnmax
        c_s_l = 0
        c_e_l = int(max(0, min(
            int(np.floor((lnmax - lon_origin) / res_x - 1e-9)) + 1,
            grid_rast.shape[1])))

        strips_g, strips_l, strips_f = [], [], []
        if c_s_r < c_e_r:
            strips_g.append(grid_rast[r_s:r_e, c_s_r:c_e_r])
            strips_l.append(moirai_land_area[r_s:r_e, c_s_r:c_e_r])
            strips_f.append(_pixel_fracs(r_s, r_e, c_s_r, c_e_r,
                                         lnmin, raster_right, ltmin, ltmax,
                                         lon_origin, lat_origin, res_x, res_y))
        if c_s_l < c_e_l:
            strips_g.append(grid_rast[r_s:r_e, c_s_l:c_e_l])
            strips_l.append(moirai_land_area[r_s:r_e, c_s_l:c_e_l])
            strips_f.append(_pixel_fracs(r_s, r_e, c_s_l, c_e_l,
                                         lon_origin, lnmax, ltmin, ltmax,
                                         lon_origin, lat_origin, res_x, res_y))
        if not strips_g:
            return None

        sub_grid   = np.concatenate(strips_g, axis=1)
        sub_land   = np.concatenate(strips_l, axis=1)
        pixel_frac = np.concatenate(strips_f, axis=1)
    else:
        col_left  = int(np.floor((lnmin - lon_origin) / res_x + 1e-9))
        col_right = int(np.floor((lnmax - lon_origin) / res_x - 1e-9))
        c_start, c_end = min(col_left, col_right), max(col_left, col_right)
        c_s = int(max(0, min(c_start, grid_rast.shape[1])))
        c_e = int(max(0, min(c_end + 1, grid_rast.shape[1])))
        if c_s == c_e:
            return None

        sub_grid   = grid_rast[r_s:r_e, c_s:c_e]
        sub_land   = moirai_land_area[r_s:r_e, c_s:c_e]
        pixel_frac = _pixel_fracs(r_s, r_e, c_s, c_e,
                                   lnmin, lnmax, ltmin, ltmax,
                                   lon_origin, lat_origin, res_x, res_y)

    # Weighted land area: pixel overlap fraction × land area of pixel.
    # Matches R's:  lu_cells$weighted_land_area = lu_cells$weight.x * lu_cells$land_area
    weighted_land = sub_land * pixel_frac

    # Total weighted land area denominator (only pixels with valid GCAM codes,
    # matching R's filter: !is.na(gcam_lu_code) & weighted_land_area > 0)
    valid_mask = (~np.isnan(sub_grid)) & (weighted_land > 0) & (~np.isnan(sub_land))
    if not np.any(valid_mask):
        return None
    total_land_area = np.sum(weighted_land[valid_mask])
    if total_land_area <= 0:
        return None

    lu_codes   = sub_grid[valid_mask].astype(int)
    land_areas = weighted_land[valid_mask]

    df_block = pd.DataFrame({'gcam_lu_code': lu_codes, 'weighted_land_area': land_areas})
    agg = df_block.groupby('gcam_lu_code')['weighted_land_area'].sum().reset_index()
    agg['weight'] = agg['weighted_land_area'] / total_land_area

    agg['gcam_reg_code']   = agg['gcam_lu_code'] // 10000
    agg['gcam_basin_code'] = agg['gcam_lu_code'] % 10000
    agg['xlon'] = ln + 1
    agg['ylat'] = lt + 1

    df_out = agg.merge(gcam_lu_df, on=['gcam_reg_code', 'gcam_basin_code'], how='inner')
    if df_out.empty:
        return None

    # Normalise weights when some raster land units are absent from gcam_lu
    # (matches R: if(sumw < 1) { weight = 1/sumw * weight })
    sumw = df_out['weight'].sum()
    if 0 < sumw < 1.0:
        df_out['weight'] = df_out['weight'] / sumw

    return df_out[['out_reg_code', 'out_lu_code', 'xlon', 'ylat', 'gcam_reg_name', 'basin_abr', 'weight']]

# --- STEP 5: LOOP THROUGH MAP RESOLUTIONS ---
for l, (surf_fn, out_csv) in enumerate(zip(elm_surf_fns, elm2gcam_ons)):
    surf_path = os.path.join(INPUT_DIR, surf_fn)
    if not os.path.exists(surf_path):
        print(f"Skipping resolution file {surf_fn}, file path not found.")
        continue
        
    print(f"Processing target resolution grid map: {surf_fn}")
    with xr.open_dataset(surf_path) as ds_surf:
        num_lon = ds_surf.sizes['lsmlon']
        num_lat = ds_surf.sizes['lsmlat']
        longxy = ds_surf['LONGXY'].values
        latixy = ds_surf['LATIXY'].values

    # FIX: Calculate grid spacing using the correct matrix axes
    # longxy varies across axis 1 (lon); latixy varies across axis 0 (lat)
    if num_lon > 1:
        half_lon = abs(longxy[0, 1] - longxy[0, 0]) / 2.0
    else:
        half_lon = 0.5

    if num_lat > 1:
        half_lat = abs(latixy[1, 0] - latixy[0, 0]) / 2.0
    else:
        half_lat = 0.5

    lonE = longxy + half_lon
    lonW = longxy - half_lon
    latN = latixy + half_lat
    latS = latixy - half_lat

    # Normalize the entire boundary matrices to -180 to 180 before passing to loop
    # This prevents scalar logic breakdown inside process_elm_cell
    lonW = np.where(lonW > 180.0, lonW - 360.0, lonW)
    lonE = np.where(lonE > 180.0, lonE - 360.0, lonE)
    lonW = np.where(lonW < -180.0, lonW + 360.0, lonW)
    lonE = np.where(lonE < -180.0, lonE + 360.0, lonE)

    num_cells = num_lon * num_lat
    
    # Process base grids
    results = []
    print(f"Starting calculation loop for {num_cells} cells...")
    for cell in range(num_cells):
        res = process_elm_cell(cell, num_lon, lonW, lonE, latS, latN, moirai_rast, gcam_lu,
                               lon_origin, lat_origin, res_x, res_y)
        if res is not None:
            results.append(res)
            
    print(f"Completed loop. Found {len(results)} intersecting cell mappings.")
    if results:
        elm2gcam_out = pd.concat(results, ignore_index=True)
        elm2gcam_out = elm2gcam_out.sort_values(by=['gcam_reg_name', 'xlon', 'ylat', 'basin_abr'])
        elm2gcam_out.columns = ["region_index", "GLU_index", "x", "y", "gcam_reg_name", "GLU_name", "Weight"]
        
        out_path = os.path.abspath(os.path.join(NEW_DIR, out_csv))
        print(f"Writing output file to: {out_path}")
        elm2gcam_out.to_csv(out_path, index=False)

print(f"Finished extracting grid mappings successfully at: {datetime.now()}")
